services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: calculetoriot:latest
    container_name: calculator-iot-backend
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://calculator-iot-postgres:5432/calculetoriot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      SPRING_REDIS_HOST: calculator-iot-redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8083:8080"
    network_mode: "bridge"
    restart: unless-stopped
